
project_id = "kxghaajojntkqrmvsngn"

[functions.enhance-job-description]
verify_jwt = false

[functions.analyze-schema]
verify_jwt = false

[functions.enrich-profile]
verify_jwt = false

[functions.generate-clarvida-report]
verify_jwt = false

[functions.process-job-requirements]
verify_jwt = false

[functions.search-contacts]
verify_jwt = false

[functions.explain-boolean]
verify_jwt = false
