
project_id = "kxghaajojntkqrmvsngn"

[functions.enhance-job-description]
verify_jwt = false

[functions.analyze-schema]
verify_jwt = false

[functions.enrich-profile]
verify_jwt = false

[functions.generate-clarvida-report]
verify_jwt = false

[functions.process-job-requirements]
verify_jwt = false

[functions.search-contacts]
verify_jwt = false

[functions.explain-boolean]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false
import_map = "./functions/send-password-reset/deno.json"
entrypoint = "./functions/send-password-reset/index.ts"

[functions.parse-document]
verify_jwt = false

[functions.test-sendgrid]
enabled = true
verify_jwt = true
import_map = "./functions/test-sendgrid/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/test-sendgrid/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/test-sendgrid/*.html" ]
