
-- Add new columns to interview_sessions table for role-specific interviews
ALTER TABLE interview_sessions 
ADD COLUMN role_title TEXT,
ADD COLUMN role_description TEXT,
ADD COLUMN interview_framework TEXT DEFAULT 'behavioral',
ADD COLUMN custom_framework_prompt TEXT,
ADD COLUMN interview_plan JSONB,
ADD COLUMN uploaded_files JSONB DEFAULT '[]'::jsonb;

-- Create interview_frameworks table for predefined frameworks
CREATE TABLE interview_frameworks (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  system_prompt TEXT NOT NULL,
  question_types JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Insert predefined interview frameworks
INSERT INTO interview_frameworks (id, name, description, system_prompt, question_types) VALUES
('star', 'STAR Method', 'Situation, Task, Action, Result framework for behavioral interviews', 
 'You are conducting a STAR method interview. Ask questions that help candidates describe specific situations, the tasks they faced, actions they took, and results they achieved. Focus on past experiences and concrete examples.',
 '["situational", "behavioral", "past_experience"]'::jsonb),
('behavioral', 'Behavioral Interview', 'Focus on past behavior to predict future performance',
 'You are conducting a behavioral interview. Ask questions about past experiences, decision-making processes, and how the candidate handled various workplace situations. Look for specific examples and patterns of behavior.',
 '["past_behavior", "decision_making", "problem_solving", "teamwork"]'::jsonb),
('competency', 'Competency-Based', 'Evaluate specific skills and competencies required for the role',
 'You are conducting a competency-based interview. Focus on evaluating the specific skills, knowledge, and abilities required for this role. Ask targeted questions that assess technical and soft skills.',
 '["technical_skills", "soft_skills", "role_specific"]'::jsonb);

-- Create interview_plans table for generated structured plans
CREATE TABLE interview_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT REFERENCES interview_sessions(id) ON DELETE CASCADE,
  plan_content JSONB NOT NULL,
  generated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  status TEXT DEFAULT 'active'
);

-- Add RLS policies for new tables
ALTER TABLE interview_frameworks ENABLE ROW LEVEL SECURITY;
ALTER TABLE interview_plans ENABLE ROW LEVEL SECURITY;

-- Frameworks are readable by all authenticated users
CREATE POLICY "Interview frameworks are viewable by authenticated users" 
  ON interview_frameworks FOR SELECT 
  TO authenticated 
  USING (true);

-- Interview plans are only accessible by the session owner
CREATE POLICY "Users can view their own interview plans" 
  ON interview_plans FOR SELECT 
  USING (EXISTS (
    SELECT 1 FROM interview_sessions 
    WHERE interview_sessions.id = interview_plans.session_id 
    AND interview_sessions.user_id = auth.uid()
  ));

CREATE POLICY "Users can create their own interview plans" 
  ON interview_plans FOR INSERT 
  WITH CHECK (EXISTS (
    SELECT 1 FROM interview_sessions 
    WHERE interview_sessions.id = interview_plans.session_id 
    AND interview_sessions.user_id = auth.uid()
  ));

CREATE POLICY "Users can update their own interview plans" 
  ON interview_plans FOR UPDATE 
  USING (EXISTS (
    SELECT 1 FROM interview_sessions 
    WHERE interview_sessions.id = interview_plans.session_id 
    AND interview_sessions.user_id = auth.uid()
  ));
